application: nich01as-com 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /s
  static_dir: static_dir

- url: /toefl/.*
  script: server.app
  login: required
  auth_fail_action: redirect

- url: /.*
  script: server.app 

libraries:
- name: jinja2
  version: latest

