application: nich01as-com 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /s
  static_dir: static_dir

- url: /_ah/spi/.*
  script: api_server.app

- url: /.*
  script: server.app 

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0


